export const IPC = {
  listSources: 'sources:list',
  startSession: 'session:start',
  stopSession: 'session:stop',
  getSession: 'session:get',
  audioChunk: 'audio:chunk',
  subtitleUpdated: 'subtitle:updated',
  sessionStatus: 'session:status',
  overlayToggle: 'overlay:toggle',
  overlaySettings: 'overlay:settings',
  exportSubtitles: 'subtitles:export',
  listSessions: 'sessions:list',
  saveSegment: 'segment:save',
  providerStatus: 'provider:status',
  getStorageSettings: 'storage:get-settings',
  chooseTemporaryDirectory: 'storage:choose-temporary-directory',
  chooseLocalMedia: 'batch:choose-local-media',
  startBatchSubtitle: 'batch:start-subtitle',
  batchProgress: 'batch:progress',
  getBatchDefaults: 'batch:get-defaults',
} as const;
